steps:
  # Step 1: Get an auth token for the Cloud Build service account
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth print-access-token > token.txt
        echo "Auth token generated."   
  # Step 2: Create API Proxies Bundle using apigeecli
  - name: 'ghcr.io/apigee/apigeecli:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Creating Bundle API Proxie..."
        apigeecli apis create bundle -o "${_APIGEE_ORG}" -n "${_API_NAME}" -p sample.zip -t $(cat token.txt)
  # Step 3: Create API Proxies Bundle using apigeecli
  - name: 'ghcr.io/apigee/apigeecli:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Deploying API Proxie..."
        apigeecli apis deploy -o "${_APIGEE_ORG}" -n "${_API_NAME}" -e "${_ENVIRONMENT}" -t $(cat token.txt)        

substitutions:
  _APIGEE_ORG: 'apigee-sandbox-non-vpc'
  _API_NAME: 'apigee-cloudbuild-test3'
  _ENVIRONMENT: 'dev'

options:
  logging: CLOUD_LOGGING_ONLY
